### ISSUE TITLE
Holding soft drop while over 1G makes the speed 1G

### ISSUE THREAD

**Issue by Prism019** [2Tie/TGMsim#21] opened 2016-11-13 22:47 UTC
If the speed is more than 1G, holding soft drop while a piece is dropping will slow it down to 1G

**Comment by 2Tie** [comment] 2016-11-15 22:49
Current commit makes soft drop add 1G to the block now, instead of setting it to 1G. Issue should be fixed.

**Comment by 2Tie** [comment] 2016-11-30 19:52
Still working on this. Trying to root out the cause.

**Comment by 2Tie** [comment] 2016-12-09 04:50
finally fixed, though it's possible there could be a better way to do this.

**Closed as completed by 2Tie** 2016-12-09 04:50 UTC

**Comment by 2Tie** [comment] 2017-06-23 20:39
after further testing, this has been improved to be accurate to at least tgm1, tgm2, and tap
